version: "3"

services:
  python-api:
      container_name: python_host
      build: ./docker/python
      volumes:
        - .:/src
      ports:
        - "8000:8000" # ホストマシンのポート8000を、docker内のポート8000に接続する
      environment:
        PMA_HOST: db
      networks:
        - mysql_bridge
        - nginx_bridge
      expose:
        - "8000"
      depends_on:
        mysql:
          condition: service_healthy

  mysql:
    container_name: mysql_host
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - data-volume:/var/lib/mysql
    restart: always
    platform: linux/amd64
    networks:
      - mysql_bridge
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+09:00']
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は30秒
      start_period: 30s

  phpmyadmin:
    container_name: phpmyadmin_host
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" #localhost:8080 で phpMyAdmin にアクセスできます
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_host

    networks:
      - mysql_bridge
  
  nginx:
    container_name: nginx_host
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
        - nginx_bridge
        - nginx_bridge
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - python-api
      - mysql

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  mysql_bridge:
    driver: bridge
  nginx_bridge:
    driver: bridge
volumes:
  data-volume: